# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 01:38
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160728_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(default='', max_length=5, validators=[blog.validators.ZipCodeValidator], verbose_name='신우편번호'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
    ]
