# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 01:58
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160801_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(max_length=5, verbose_name='신우편번호'),
        ),
    ]
