# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemongo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catched_date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemongo.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('catched_pokemon', models.ManyToManyField(through='pokemongo.CatchInfo', to='pokemongo.Pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='catchinfo',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemongo.Trainer'),
        ),
    ]
