# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Person', verbose_name='포켓몬 트레이너')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Place', verbose_name='포켓몬 잡은 장소')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon', verbose_name='잡은 포켓몬')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='person',
        ),
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pokemon',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
